blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/eclipse-qsos/qsos/discussions
    about: Pour poser des questions ou discuter avec la communauté
  - name: 📧 Contact Eclipse QSOS
    url: mailto:qsos-dev@eclipse.org
    about: Contacter l'équipe de développement par email
  - name: 🌐 Eclipse QSOS Website
    url: https://projects.eclipse.org/projects/technology.qsos
    about: En savoir plus sur le projet Eclipse QSOS